name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        pip3 install awscli boto3

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-1

    - name: Install nginx
      run: |
        sudo apt-get install -y nginx

    - name: Copy nginx configuration
      run: |
        sudo cp /etc/nginx/nginx.conf /etc/nginx/sites-available/
        sudo ln -s /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled/
        sudo service nginx restart

    - name: Deploy code to EC2 instance
      run: |
        ssh ec2-user@${{ secrets.EC2_INSTANCE_IP }} 'mkdir -p /var/www/myapp'
        scp -r ./ ec2-user@${{ secrets.EC2_INSTANCE_IP }}:/var/www/myapp/
