name: Deploy to NGINX Server
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.2.12
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-host: ${{ secrets.SSH_HOST }}
        ssh-username: ${{ secrets.SSH_USERNAME }}
        local-path: './dist'
        remote-path: '/var/www/html'

    - name: Check status
      run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'service nginx status'
