name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Create EC2 instance
      run: |
        aws ec2 run-instances \
          --image-id ami-0fa1de1d60de6a97e \
          --count 1 \
          --instance-type t2.micro \
          --key-name cc10 \
          --security-group-ids sg-05519f83a6e1764e5 \
          --subnet-id subnet-09603566a8a1dca06 \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=<cc_10>}]'

    - name: Wait for instance to start
      run: |
        # Add a wait command to wait for the instance to start
        # For example:
          aws ec2 wait instance-status-ok --instance-ids i-0e130ba2da9d7a660

    - name: Deploy application
      run: |
        # Add your deployment commands here
        # For example:
          scp -i "C:\Users\Divya\Downloads\cc10.pem" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./dist/* ec2-user@34.235.89.91:/etc/nginx/conf.d/

    - name: Configure Nginx
      run: |
        sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
        sudo rm /etc/nginx/sites-available/default
        sudo sh -c 'echo "server {
            listen 80;
            location / {
                proxy_pass http://34.235.89.91;
                proxy_set_header Host \$host;
                proxy_set_header X-Real-IP \$remote_addr;
                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            }
        }" > /etc/nginx/sites-available/default'
        sudo service nginx restart
